version: "3.5"
services:
    virus:
        build: .
        container_name: virus
        restart: always
        networks:
            - db
        volumes:
            - ./code:/var/www/virus
            - ./data:/data
            - ./backup:/backup
        env_file:
            - env/mysql
            - env/site
        ports:
            - 80:80
    db:
        image: mysql
        container_name: virus_mysql
        restart: always
        networks:
            - db
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql_startup:/docker-entrypoint-initdb.d
        env_file:
            - env/mysql
    phpmyadmin:
        image: 157239n/phpmyadmin
        container_name: virus_phpmyadmin
        restart: always
        networks:
            - db
        env_file:
            - env/site
        ports:
            - 5000:5000
networks:
    db:
